import { defaultCandidate, policyFor, validateModel } from "./model-policy.js";
import type { RenderOptions, TargetId } from "./types.js";

const GENERATED_NOTICE = "Generated by @fpgskills/task-executor. Do not edit directly.";

export function renderAdapter(options: RenderOptions): string {
  const selection = options.profile ?? options.selection ?? defaultCandidate(policyFor(options.target));
  validateModel(selection.model);
  const caller = options.callerPath ?? "the task-executor-routing skill in this bundle";
  options = { ...options, selection, metadata: { ...options.metadata, description: `${options.metadata.description} Read ${caller} before dispatch.${options.profile ? " Named alternative: select only after routing assessment." : " Start with the configured cheap profile."}` } };
  switch (options.target) {
    case "codex":
      return renderCodex(options);
    case "opencode":
      return renderOpenCode(options);
    case "cursor":
      return renderCursor(options);
    case "claude-code":
      return renderClaudeCode(options);
    case "antigravity":
      return renderAntigravity(options);
    case "generic":
      return renderGeneric(options);
  }
}

function renderCodex({ metadata, prompt, profile, selection }: RenderOptions): string {
  const name = profile ? `${metadata.id}-${profile.name}` : metadata.id;
  const fields = [
    `# ${GENERATED_NOTICE}`,
    `# Task Executor contract version: ${metadata.version}`,
    `name = ${JSON.stringify(name)}`,
    `description = ${JSON.stringify(metadata.description)}`,
  ];
  fields.push(`model = ${JSON.stringify(selection!.model)}`);
  if (selection?.reasoningEffort) fields.push(`model_reasoning_effort = ${JSON.stringify(selection.reasoningEffort)}`);
  fields.push(`developer_instructions = ${JSON.stringify(prompt)}`);
  return `${fields.join("\n")}\n`;
}

function renderOpenCode({ metadata, prompt, profile, selection }: RenderOptions): string {
  const model = `\nmodel: ${yamlString(selection!.model)}`;
  const effort = selection?.reasoningEffort ? `\nreasoningEffort: ${yamlString(selection.reasoningEffort)}` : "";
  return `---\ndescription: ${yamlString(metadata.description)}\nmode: subagent${model}${effort}\n---\n\n<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function renderCursor({ metadata, prompt, profile, selection }: RenderOptions): string {
  const name = profile ? `${metadata.id}-${profile.name}` : metadata.id;
  const model = cursorModel(selection!);
  return `---\nname: ${name}\ndescription: ${yamlString(metadata.description)}\nmodel: ${yamlString(model)}\nreadonly: false\nis_background: false\n---\n\n<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function cursorModel(profile: NonNullable<RenderOptions["profile"]>): string {
  if (!profile.reasoningEffort) return profile.model;
  if (profile.model.includes("[")) return profile.model;
  return `${profile.model}[effort=${profile.reasoningEffort}]`;
}

function renderClaudeCode({ metadata, prompt, profile, selection }: RenderOptions): string {
  const name = profile ? `${metadata.id}-${profile.name}` : metadata.id;
  const model = selection!.model;
  return `---\nname: ${name}\ndescription: ${yamlString(metadata.description)}\nmodel: ${yamlString(model)}\n---\n\n<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function renderAntigravity({ metadata, prompt, profile, selection }: RenderOptions): string {
  const name = profile ? `${metadata.id}-${profile.name}` : metadata.id;
  const model = selection!.model;
  return `---\nname: ${name}\ndescription: ${yamlString(metadata.description)}\nmainAgent: false\nsubagent: true\nmodel: ${yamlString(model)}\ncommandExecutionPolicy: sandbox\ntools:\n  - view_file\n  - find_by_name\n  - grep_search\n  - write_to_file\n  - replace_file_content\n  - multi_replace_file_content\n  - run_command\n---\n\n<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function renderGeneric({ metadata, prompt, selection }: RenderOptions): string {
  return `<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\nCaller: ${metadata.description}\n\nRequested configuration: ${selection!.model}${selection?.reasoningEffort ? ` (reasoning: ${selection.reasoningEffort})` : ""}. Bind this explicitly through the host before launch; this Markdown cannot select a model itself.\n\n${prompt}\n`;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

export function targetAdapterDirectory(target: TargetId): string {
  return target;
}
