import assert from "node:assert/strict";
import { test } from "node:test";
import { renderAdapter } from "./render.js";
import type { AgentMetadata, TargetId } from "./types.js";

const metadata: AgentMetadata = {
  id: "task-executor",
  displayName: "Task Executor",
  version: "1.0.0",
  description: "Invoke only when explicitly requested.",
  manualInvocationOnly: true,
  defaultModel: "inherit",
  targets: ["codex", "opencode", "cursor", "claude-code", "antigravity", "generic"],
};

test("every adapter contains the canonical prompt and version", () => {
  for (const target of metadata.targets) {
    const rendered = renderAdapter({ metadata, prompt: "CANONICAL PROMPT", target });
    assert.match(rendered, /CANONICAL PROMPT/);
    assert.match(rendered, /1\.0\.0/);
    assert.match(rendered, /Generated by @fpgskills\/task-executor/);
  }
});

test("named profiles produce native model metadata", () => {
  const targets: TargetId[] = ["codex", "opencode", "cursor", "claude-code", "antigravity"];
  for (const target of targets) {
    const rendered = renderAdapter({
      metadata,
      prompt: "PROMPT",
      target,
      profile: { name: "luna", model: "vendor/luna" },
    });
    assert.match(rendered, /vendor\/luna/);
    assert.match(rendered, /task-executor-luna|description/);
  }
});

test("the generic adapter has no platform metadata", () => {
  const rendered = renderAdapter({ metadata, prompt: "PROMPT", target: "generic" });
  assert.doesNotMatch(rendered, /^---/);
  assert.match(rendered, /PROMPT/);
});
