import assert from "node:assert/strict";
import { test } from "node:test";
import { renderAdapter } from "./render.js";
import type { AgentMetadata, TargetId } from "./types.js";

const metadata: AgentMetadata = {
  id: "task-executor",
  displayName: "Task Executor",
  version: "1.0.0",
  description: "Invoke only when explicitly requested.",
  manualInvocationOnly: true,
  defaultModel: "inherit",
  targets: ["codex", "opencode", "cursor", "claude-code", "antigravity", "generic"],
};

test("every adapter contains the canonical prompt and version", () => {
  for (const target of metadata.targets) {
    const rendered = renderAdapter({ metadata, prompt: "CANONICAL PROMPT", target });
    assert.match(rendered, /CANONICAL PROMPT/);
    assert.match(rendered, /1\.0\.0/);
    assert.match(rendered, /Generated by @fpgskills\/task-executor/);
  }
});

test("named profiles produce native model and effort metadata where supported", () => {
  const targets: TargetId[] = ["codex", "opencode", "cursor", "claude-code", "antigravity"];
  for (const target of targets) {
    const rendered = renderAdapter({
      metadata,
      prompt: "PROMPT",
      target,
      profile: { name: "luna", model: "vendor/luna", reasoningEffort: "max" },
    });
    assert.match(rendered, /vendor\/luna/);
    assert.match(rendered, /task-executor-luna|description/);
    if (target === "codex") assert.match(rendered, /model_reasoning_effort = "max"/);
    if (target === "opencode") assert.match(rendered, /reasoningEffort: "max"/);
    if (target === "cursor") assert.match(rendered, /vendor\/luna\[effort=max\]/);
    if (target === "claude-code" || target === "antigravity") assert.doesNotMatch(rendered, /max/);
  }
});

test("Cursor profiles without effort keep the model ID unchanged", () => {
  const rendered = renderAdapter({
    metadata,
    prompt: "PROMPT",
    target: "cursor",
    profile: { name: "luna", model: "gpt-5.6-luna" },
  });
  assert.match(rendered, /model: "gpt-5\.6-luna"/);
  assert.doesNotMatch(rendered, /\[effort=/);
});

test("Cursor does not wrap a model ID that already contains parameters", () => {
  const rendered = renderAdapter({
    metadata,
    prompt: "PROMPT",
    target: "cursor",
    profile: { name: "luna", model: "gpt-5.6-luna[effort=max]", reasoningEffort: "max" },
  });
  assert.match(rendered, /model: "gpt-5\.6-luna\[effort=max\]"/);
  assert.doesNotMatch(rendered, /\[effort=max\]\[effort=/);
});

test("the generic adapter has no platform metadata", () => {
  const rendered = renderAdapter({ metadata, prompt: "PROMPT", target: "generic" });
  assert.doesNotMatch(rendered, /^---/);
  assert.match(rendered, /PROMPT/);
});
