import type { RenderOptions, TargetId } from "./types.js";

const GENERATED_NOTICE = "Generated by @fpgskills/task-executor. Do not edit directly.";

export function renderAdapter(options: RenderOptions): string {
  switch (options.target) {
    case "codex":
      return renderCodex(options);
    case "opencode":
      return renderOpenCode(options);
    case "cursor":
      return renderCursor(options);
    case "claude-code":
      return renderClaudeCode(options);
    case "antigravity":
      return renderAntigravity(options);
    case "generic":
      return renderGeneric(options);
  }
}

function renderCodex({ metadata, prompt, profile }: RenderOptions): string {
  const name = profile ? `${metadata.id}-${profile.name}` : metadata.id;
  const fields = [
    `# ${GENERATED_NOTICE}`,
    `# Task Executor contract version: ${metadata.version}`,
    `name = ${JSON.stringify(name)}`,
    `description = ${JSON.stringify(metadata.description)}`,
  ];
  if (profile) fields.push(`model = ${JSON.stringify(profile.model)}`);
  if (profile?.reasoningEffort) fields.push(`model_reasoning_effort = ${JSON.stringify(profile.reasoningEffort)}`);
  fields.push(`developer_instructions = ${JSON.stringify(prompt)}`);
  return `${fields.join("\n")}\n`;
}

function renderOpenCode({ metadata, prompt, profile }: RenderOptions): string {
  const model = profile ? `\nmodel: ${yamlString(profile.model)}` : "";
  const effort = profile?.reasoningEffort ? `\nreasoningEffort: ${yamlString(profile.reasoningEffort)}` : "";
  return `---\ndescription: ${yamlString(metadata.description)}\nmode: subagent${model}${effort}\n---\n\n<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function renderCursor({ metadata, prompt, profile }: RenderOptions): string {
  const name = profile ? `${metadata.id}-${profile.name}` : metadata.id;
  const model = profile ? cursorModel(profile) : "inherit";
  return `---\nname: ${name}\ndescription: ${yamlString(metadata.description)}\nmodel: ${yamlString(model)}\nreadonly: false\nis_background: false\n---\n\n<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function cursorModel(profile: NonNullable<RenderOptions["profile"]>): string {
  return profile.reasoningEffort ? `${profile.model}-${profile.reasoningEffort}` : profile.model;
}

function renderClaudeCode({ metadata, prompt, profile }: RenderOptions): string {
  const name = profile ? `${metadata.id}-${profile.name}` : metadata.id;
  const model = profile?.model ?? "inherit";
  return `---\nname: ${name}\ndescription: ${yamlString(metadata.description)}\nmodel: ${yamlString(model)}\n---\n\n<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function renderAntigravity({ metadata, prompt, profile }: RenderOptions): string {
  const name = profile ? `${metadata.id}-${profile.name}` : metadata.id;
  const model = profile?.model ?? "inherit";
  return `---\nname: ${name}\ndescription: ${yamlString(metadata.description)}\nmainAgent: false\nsubagent: true\nmodel: ${yamlString(model)}\ncommandExecutionPolicy: sandbox\ntools:\n  - view_file\n  - find_by_name\n  - grep_search\n  - write_to_file\n  - replace_file_content\n  - multi_replace_file_content\n  - run_command\n---\n\n<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function renderGeneric({ metadata, prompt }: RenderOptions): string {
  return `<!-- ${GENERATED_NOTICE} Contract version: ${metadata.version}. -->\n\n${prompt}\n`;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

export function targetAdapterDirectory(target: TargetId): string {
  return target;
}
