export const CANONICAL_FILES = [
  "SKILL.md",
  "agents/openai.yaml",
  "references/bottlenecks.md",
  "references/discovery.md",
  "references/execution.md",
  "references/grpc.md",
  "references/plan-and-safety.md",
  "references/plan-schema.md",
  "references/reporting.md",
  "references/rest.md",
  "references/run-schema.md",
  "references/workloads.md",
  "scripts/render-report.mjs",
  "scripts/validate-plan.mjs",
  "assets/k6/grpc-stream.js",
  "assets/k6/grpc-unary.js",
  "assets/k6/http-endpoint.js",
  "assets/k6/http-journey.js",
  "assets/k6/lib/reporter.js",
  "assets/grafana/compose.yaml.tmpl",
  "assets/grafana/prometheus.yml",
  "assets/grafana/provisioning/dashboards/provider.yaml",
  "assets/grafana/provisioning/dashboards/k6-local.json",
  "assets/grafana/provisioning/datasources/prometheus.yaml",
  "assets/monitor/collect-posix.sh",
  "assets/monitor/collect-windows.ps1",
] as const;
